# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./furnace-aws/furnace_aws.go
    binary: furnace-aws
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
  - main: ./furnace-do/furnace_do.go
    binary: furnace-do
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
  - main: ./furnace-gcp/furnace_gcp.go
    binary: furnace-gcp
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
