language: go

go:
  - master

before_install:
    - go get github.com/mattn/goveralls
    - mkdir -p $HOME/.config/go-furnace
    - cp $TRAVIS_BUILD_DIR/templates/aws_furnace_config.yaml $HOME/.config/go-furnace
    - cp $TRAVIS_BUILD_DIR/templates/cloud_formation.template $HOME/.config/go-furnace

install: make get-deps-all

script:
    - ./test-coverage.sh
